version: '3.8'

services:
  mysql:
      image: mysql:8.0
      container_name: leave-management-mysql

      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: leave_management

      ports:
        - "3306:3306"

      volumes:
        - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  eurekaserver:
    image: sahilsoni234/eurekaserver:latest

    container_name: eurekaserver

    ports:
      - "8761:8761"

  apigateway:
    image: sahilsoni234/apigateway:latest

    container_name: apigateway

    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

    ports:
      - "8080:8080"

    depends_on:
      - eurekaserver
      - zipkin

  authservice:
    image: sahilsoni234/authservice:latest

    container_name: authservice

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leave_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8081:8081"

    depends_on:
      - mysql
      - eurekaserver
      - zipkin

  employeeservice:
    image: sahilsoni234/employeeservice:latest

    container_name: employeeservice

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leave_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8082:8082"

    depends_on:
      - mysql
      - eurekaserver
      - zipkin

  leaveservice:
    image: sahilsoni234/leaveservice:latest

    container_name: leaveservice

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leave_management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    ports:
      - "8083:8083"

    depends_on:
      - mysql
      - eurekaserver
      - rabbitmq
      - zipkin

  notificationservice:
    image: sahilsoni234/notificationservice:latest

    container_name: notificationservice

    ports:
      - "8084:8084"

    depends_on:
      - rabbitmq
      - eurekaserver
      - zipkin

    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    restart: unless-stopped

volumes:
  mysql-data: